package models

// SimulationRequest xxx
type SimulationRequest struct {
	UpdatedAt                 uint
	InitialPersonCount        uint
	ExtensionPercentage       uint
	MonthlyGrowthRate         uint
	SameVehicle               uint
	SameCategory              uint
	AlternateCategory1        uint
	AlternateCategory2        uint
	SamePrice                 uint
	AlternatePrice1           uint
	AlternatePrice2           uint
	Popularity0               uint
	Popularity1               uint
	Popularity2               uint
	Popularity3               uint
	Popularity4               uint
	Popularity5               uint
	Popularity6               uint
	Popularity7               uint
	Popularity8               uint
	Popularity9               uint
	SubscriptionPriceFactor   uint
	SubscriptionLength        uint
	SubscriptionInSeconds     uint
	MonthsInSubscription      uint
	MarketStart               uint
	MarketLimitMin            uint
	MarketLimitMax            uint
	LeaseInitialPercentage    uint
	AnnualAccident            uint
	DailyAccident             uint
	VehicleTax                uint
	VehicleInterest           uint
	InsuranceMin              uint
	InsuranceMax              uint
	ResellMin                 uint
	ResellMax                 uint
	AbsentSameCategory        uint
	AbsentAlternate1          uint
	AbsentLeaveService        uint
	AbsentNextOption          uint
	AbsentNextLeaveService    uint
	VehicleLimit              uint
	VehicleLimitIncreaseValue uint
	VehicleLimitIncreaseLower uint
	VehicleLimitIncreaseUpper uint
	SimulationStart           uint
	SimulationEnd             uint
	SubscriptionPaymentMethod uint
	PriceFactorLogA           uint
	PriceFactorLogB           uint
	PriceFactorLogC           uint
	PriceFactorLogD           uint
	PriceFactorSquareA        uint
	PriceFactorSquareB        uint
	PriceFactorSquareC        uint
	PriceFactorSquareD        uint
	YearlyDepreciationMethod  uint
	StepwiseLower0            uint
	StepwiseUpper0            uint
	StepwiseValue0            uint
	StepwiseLower1            uint
	StepwiseUpper1            uint
	StepwiseValue1            uint
	StepwiseLower2            uint
	StepwiseUpper2            uint
	StepwiseValue2            uint
	StepwiseLower3            uint
	StepwiseUpper3            uint
	StepwiseValue3            uint
	StepwiseLower4            uint
	StepwiseUpper4            uint
	StepwiseValue4            uint
	StepwiseLower5            uint
	StepwiseUpper5            uint
	StepwiseValue5            uint
	StepwiseLower6            uint
	StepwiseUpper6            uint
	StepwiseValue6            uint
	StepwiseLower7            uint
	StepwiseUpper7            uint
	StepwiseValue7            uint
	StepwiseLower8            uint
	StepwiseUpper8            uint
	StepwiseValue8            uint
	StepwiseLower9            uint
	StepwiseUpper9            uint
	StepwiseValue9            uint
	StepwiseDefault           uint
}
